### PR TITLE
capture code stacktrace

### LINKED ISSUE #22: automatically update license when 'model_generated.go' is generated
This is a follow-up of #17 , in particular [this comment](https://github.com/elastic/apm-data/pull/17#discussion_r1105931008).

When generating the `model_generated.go` through the `make generate` command, the generated file does not contain the required license headers.

As a consequence, we have to also run `make update-licenses` in order to fix that.

Making the `make generate` also update the license in `model_generated.go` would remove the need to have execute a separate command.

### LINKED ISSUE #177: Map OTel `code.stacktrace` attribute top-level
Once https://github.com/open-telemetry/semantic-conventions/pull/435 lands, we need to map the OTel `code.stacktrace` attribute top-level (instead of into labels) so we can display stacktraces on spans for OTel-based agents.

### PR DESCRIPTION
**Pull request by SylvainJuge**
- simple fix for #22
- captures `code.stacktrace` otel attribute and stores it in `span.code.stacktrace`.

Fixes #22 
Fixes #177 

Tested manually when combined with:
- an otel agent that sends `code.stacktrace` attribute
- https://github.com/elastic/apm-server/pull/12096 PR to include the new field

<details>

<summary>Sample JSON span document captured when testing manually</summary>

```
{
  "_index": ".ds-traces-apm-default-2023.11.23-000001",
  "_id": "Beec_IsBlEx8DpqSNsdT",
  "_version": 1,
  "_score": 0,
  "_source": {
    "parent": {
      "id": "999b27462a952621"
    },
    "agent": {
      "name": "opentelemetry/java",
      "version": "1.30.1"
    },
    "process": {
      "pid": 1071606,
      "executable": "/home/sylvain/.sdkman/candidates/java/17.0.8-tem/bin/java"
    },
    "code": {
      "stacktrace": "java.lang.Throwable\n\tat co.elastic.otel.ElasticSpanProcessor.captureStackTrace(ElasticSpanProcessor.java:81)\n\tat co.elastic.otel.ElasticSpanProcessor.onEnd(ElasticSpanProcessor.java:56)\n\tat io.opentelemetry.sdk.trace.MultiSpanProcessor.onEnd(MultiSpanProcessor.java:52)\n\tat io.opentelemetry.sdk.trace.SdkSpan.endInternal(SdkSpan.java:451)\n\tat io.opentelemetry.sdk.trace.SdkSpan.end(SdkSpan.java:431)\n\tat io.opentelemetry.javaagent.instrumentation.opentelemetryapi.trace.ApplicationSpan.end(ApplicationSpan.java:140)\n\tat co.elastic.apm.opbeans.controllers.APIRestController.orders(APIRestController.java:140)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.web.method.support.InvocableHandlerM"
    },
    "processor": {
      "event": "span"
    },
    "labels": {
      "process_runtime_description": "Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.8+7",
      "elastic_span_local_root_id": "8e80b8c8b8a749f6",
      "agentdev_worktree": "span-stack",
      "elastic_span_is_local_root": "false",
      "thread_name": "http-nio-8080-exec-3",
      "agentdev_agent_type": "elastic-otel",
      "telemetry_auto_version": "elastic-0.0.1-SNAPSHOT-otel-1.30.0",
      "process_command_args": [
        "/home/sylvain/.sdkman/candidates/java/17.0.8-tem/bin/java",
        "-javaagent:/home/sylvain/dev/elastic-otel-java_span-stack/agent/build/libs/elastic-otel-javaagent-0.0.1-SNAPSHOT.jar",
        "-jar",
        "./target/opbeans-0.0.1-SNAPSHOT.jar"
      ]
    },
    "observer": {
      "hostname": "apm-server-apm-server-5bccdfb694-5qsg2",
      "type": "apm-server",
      "version": "8.12.0"
    },
    "trace": {
      "id": "a323e1ee1efb4b792b96d37f6960fcf0"
    },
    "@timestamp": "2023-11-23T14:36:11.772Z",
    "data_stream": {
      "namespace": "default",
      "type": "traces",
      "dataset": "apm"
    },
    "numeric_labels": {
      "thread_id": 50,
      "elastic_span_self_time": 4026320
    },
    "service": {
      "node": {
        "name": "sylvain-elastic"
      },
      "environment": "sylvain-test",
      "name": "opbeans-elastic-otel",
      "runtime": {
        "name": "OpenJDK Runtime Environment",
        "version": "17.0.8+7"
      },
      "language": {
        "name": "java"
      },
      "version": "1.0"
    },
    "host": {
      "hostname": "sylvain-elastic",
      "os": {
        "type": "linux",
        "platform": "linux",
        "full": "Linux 6.5.0-13-generic"
      },
      "name": "sylvain-elastic",
      "architecture": "amd64"
    },
    "event": {
      "agent_id_status": "missing",
      "ingested": "2023-11-23T14:36:17Z",
      "outcome": "unknown"
    },
    "span": {
      "duration": {
        "us": 191140
      },
      "representative_count": 1,
      "subtype": "internal",
      "name": "OpenTelemetry orders",
      "id": "8450ed499aeb1204",
      "type": "app"
    },
    "timestamp": {
      "us": 1700750171772963
    }
  },
  "fields": {
    "labels.process_command_args": [
      "/home/sylvain/.sdkman/candidates/java/17.0.8-tem/bin/java",
      "-javaagent:/home/sylvain/dev/elastic-otel-java_span-stack/agent/build/libs/elastic-otel-javaagent-0.0.1-SNAPSHOT.jar",
      "-jar",
      "./target/opbeans-0.0.1-SNAPSHOT.jar"
    ],
    "host.os.full.text": [
      "Linux 6.5.0-13-generic"
    ],
    "labels.process_runtime_description": [
      "Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.8+7"
    ],
    "host.os.full": [
      "Linux 6.5.0-13-generic"
    ],
    "labels.elastic_span_is_local_root": [
      "false"
    ],
    "host.hostname": [
      "sylvain-elastic"
    ],
    "process.pid": [
      1071606
    ],
    "service.language.name": [
      "java"
    ],
    "labels.thread_name": [
      "http-nio-8080-exec-3"
    ],
    "labels.telemetry_auto_version": [
      "elastic-0.0.1-SNAPSHOT-otel-1.30.0"
    ],
    "processor.event": [
      "span"
    ],
    "agent.name": [
      "opentelemetry/java"
    ],
    "host.name": [
      "sylvain-elastic"
    ],
    "event.agent_id_status": [
      "missing"
    ],
    "event.outcome": [
      "unknown"
    ],
    "labels.agentdev_agent_type": [
      "elastic-otel"
    ],
    "labels.agentdev_worktree": [
      "span-stack"
    ],
    "host.os.type": [
      "linux"
    ],
    "service.runtime.version": [
      "17.0.8+7"
    ],
    "span.id": [
      "8450ed499aeb1204"
    ],
    "data_stream.type": [
      "traces"
    ],
    "span.type": [
      "app"
    ],
    "host.architecture": [
      "amd64"
    ],
    "timestamp.us": [
      1700750171772963
    ],
    "code.stacktrace": [
      "java.lang.Throwable\n\tat co.elastic.otel.ElasticSpanProcessor.captureStackTrace(ElasticSpanProcessor.java:81)\n\tat co.elastic.otel.ElasticSpanProcessor.onEnd(ElasticSpanProcessor.java:56)\n\tat io.opentelemetry.sdk.trace.MultiSpanProcessor.onEnd(MultiSpanProcessor.java:52)\n\tat io.opentelemetry.sdk.trace.SdkSpan.endInternal(SdkSpan.java:451)\n\tat io.opentelemetry.sdk.trace.SdkSpan.end(SdkSpan.java:431)\n\tat io.opentelemetry.javaagent.instrumentation.opentelemetryapi.trace.ApplicationSpan.end(ApplicationSpan.java:140)\n\tat co.elastic.apm.opbeans.controllers.APIRestController.orders(APIRestController.java:140)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.web.method.support.InvocableHandlerM"
    ],
    "observer.type": [
      "apm-server"
    ],
    "observer.version": [
      "8.12.0"
    ],
    "agent.version": [
      "1.30.1"
    ],
    "parent.id": [
      "999b27462a952621"
    ],
    "numeric_labels.thread_id": [
      50
    ],
    "span.representative_count": [
      1
    ],
    "span.name": [
      "OpenTelemetry orders"
    ],
    "labels.elastic_span_local_root_id": [
      "8e80b8c8b8a749f6"
    ],
    "numeric_labels.elastic_span_self_time": [
      4026320
    ],
    "service.node.name": [
      "sylvain-elastic"
    ],
    "trace.id": [
      "a323e1ee1efb4b792b96d37f6960fcf0"
    ],
    "span.duration.us": [
      191140
    ],
    "process.executable": [
      "/home/sylvain/.sdkman/candidates/java/17.0.8-tem/bin/java"
    ],
    "service.environment": [
      "sylvain-test"
    ],
    "service.name": [
      "opbeans-elastic-otel"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "service.runtime.name": [
      "OpenJDK Runtime Environment"
    ],
    "span.subtype": [
      "internal"
    ],
    "observer.hostname": [
      "apm-server-apm-server-5bccdfb694-5qsg2"
    ],
    "event.ingested": [
      "2023-11-23T14:36:17.000Z"
    ],
    "@timestamp": [
      "2023-11-23T14:36:11.772Z"
    ],
    "service.version": [
      "1.0"
    ],
    "host.os.platform": [
      "linux"
    ],
    "data_stream.dataset": [
      "apm"
    ]
  }
}
```
</details>

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -14,9 +14,11 @@ protolint:
 gomodtidy:
 	go mod tidy -v
 
-generate:
+generate_code:
```
Comment (SylvainJuge) [inline Makefile:17]: [for reviewer] this is not required for this PR, and there is probably a better way to deal with this.

Comment (axw) [reply Makefile:17]: This seems fine to me, thanks

File: model/modeljson/internal/span.go [hunk 2]
```diff
@@ -22,6 +22,7 @@ type Span struct {
 	Composite           *SpanComposite     `json:"composite,omitempty"`
 	Destination         *SpanDestination   `json:"destination,omitempty"`
 	DB                  *DB                `json:"db,omitempty"`
+	Code                *Code              `json:"code,omitempty"`
```
Comment (axw) [inline model/modeljson/internal/span.go:25]: Is this change required? Why are we adding it both here and in `document.go`? Should we be mapping it as `code.stacktrace`, or `span.code.stacktrace`? I would expect the former, since that's what we're planning to do for OTel attributes in the future. Also I don't see any code that sets either modeljson type's Code field from the modelpb type...?

Comment (SylvainJuge) [reply model/modeljson/internal/span.go:25]: I wasn't aware that we plan to keep the `span` namespace, in which case that makes sense to write it to `span.code.stacktrace`.

I don't know why I had to add it to both places, I just followed the instructions to add a new otel field.
From what I understand I have to decide adding this field in either `document.go` or `span.go`, which of the two is preferable ?

Comment (axw) [reply model/modeljson/internal/span.go:25]: > I wasn't aware that we plan to keep the span namespace, in which case that makes sense to write it to span.code.stacktrace.

No, the opposite - we will stop nesting so many things under `span` in the future. There will be `span.id` and things like that, but in the future attributes will essentially be written as they come (e.g. the `code.stacktrace` OTel attribute would be mapped as `code.stacktrace` in the ES docs).

> From what I understand I have to decide adding this field in either document.go or span.go, which of the two is preferable ?

`document.go`, so it ends up at the top level

**Comment by SylvainJuge** [comment]
Hi @axw, I think it's ready for review, do you think you can take a look at it ?
I have only tested it manually on my side when combined with https://github.com/elastic/apm-server/pull/12096

**Review by axw — APPROVED** [review]
